.PP
We normally make a distinction between
.I subjective
and
.I objective
probabilities.
.[
Popper magic knowledge probability
.]
These are the two interpretations of probabilities.
The subjective probability refers to an epistemic aspect of an event,
for instance our confidence that a certain proposition about that event is true.
Objective probabilities are those that exist in Nature no matter what.
That is,
we make metaphysical claims when using that concept.
For instance, each of us carries $approx 75.8$ new mutations.\**
.FS
The mutation rate for humans is in the order of magnitude $1.24 \[mu] 10 sup -8$ per base pairs per generation.
.[
estimating mutation rate
.]
Each of us carries around $3.055 \[mu] 10 sup 9$ base pairs per chromosome set
.[
complete sequence human genome 
.]
and we are diploid organisms (we have two sets of chromosomes, one from each parent).
Therefore both you and I have got about 75.76 new mutations ($1.24 \[mu] 10 sup -8 \[mu] 3.055 \[mu] 10 sup 9  \[mu] 2$) from our parents.
.FE
.so dna/mutations.ms
Mutation occurs all over the human genome at a rate from about $10 sup -9$ to $10 sup -8$ per base pair per generation.
Still, the size of our genome $approx 3.055 \[mu] 10 sup 9$ ensures that all of us are mutants.
It has been like that since long before we became \f[I]Homo sapiens\f[P].
See Figure 1 for more information on mutations.
There is a related concept, \f[I]wild type\f[P], which refers to the dominating variety in the population.
.PP
As we mentioned above,
Popper makes further distinctions between two kinds of objective probabilities,
namely frequency and propensity interpretations of probability.
.[
Popper propensity
.]
The frequency interpretation claims that a probability can only be understood,
and be estimated,
through a series of measurements.
Mathematically, in such a series,
we reach the probability in the limit when the series length approaches infinity.
.PP
A propensity should be understood as the probability for a single event.
.[
Popper propensity 1959 
.]
Popper was convinced that probabilities are \[oq]physically real\[cq],
.QP
.vs 12
.ps 10
that they must be physical propensities,
abstract relational properties of the physical situation,
like Newtonian forces,
and \[oq]real\[cq],
not only in the sense that they could influence the experimental results,
but also in the sense that they could,
under certain circumstances (coherence), interfere with one another.
.[ (
Popper propensity 1959 
.], p. 28)
.LP
That is, the key property of a propensity is that it behaves analogously to a force.
Mutations are such forces.
One opponent to Popper's idea of the assignment of probabilities to single events was.
.[ 
#
probability statistics truth 1957
.]
von Mises talks about
.I classes
or
.I collectives.
.QP
.vs 12
.ps 10
When we speak of \[oq]the probability of death\[cq],
the exact meaning of this expression can be defined in the following way only.
We must not think of an individual,
but of a certain class as a whole, e.g.,
\[oq]all insured men forty-one years old a given country and not engaged in certain dangerous occupations\[cq].
A probability of death is attached to this class of men or to another class that can be defined in a similar way.
.[
probability statistics truth 1957
.]
.LP
Given a defined class of objects we can estimate a meaningful probability.
For instance
.QP
.vs 12
.ps 10
The phrase \[oq]probability of death\[cq],
when it refers to a single person,
has no meaning at all for us.
This is one of the most important consequences of our definition of probability and we shall discuss this point in greater detail later on.
.[ (
probability statistics truth 1957
.], p. 11)
.LP
The collective means in von Mises\[aq] vocabulary basically an experimental series. 
The adherent of the propensity theory does not dispute that a series of measurements is needed for estimating the value of a probability.
However, he or she regard the frequency approach as a method,
and its interpretation as an epistemic problem.
.PP
Popper argues that von Mises position leads to a contradiction if there is a heterogeneity in such a series,
for instance a series which includes throws of a homogenous and symmetrical die and a loaded one, with (say) a majority of throws made with a true one.
Then the frequentist will need to introduce a new class or collective.
.PP
Thence, 
the frequentist is forced to accept the propensity interpretation.
.QP
.vs 12
.ps 10
All this means that the frequency theorist is forced to introduce a modification of his theory\[em]apparently a very slight one.
He will now say that an admissible sequence of events (a reference sequence,
a \[oq]collective\[cq]) must always be a sequence of repeated experiments.
.LP
In the following,
when we talk about mutants and wild types think about heterogeneity and that individuals may have different propensities.
