.LP
Probability, possibility and dynamical systems
.ID
One locus two alleles
stability, invasibility and the role of propensities when rare
We should avoid the fitness concept (interpreted as a propensity or not)
Instead focus on selection as a process.
We are not guaranteed that the propagation of a trait can be
summarized in a single statistic
.DE
.LP
The Price equation leads us to dynamical systems modelling the change in gene frequencies between generations.
I discuss them briefly from the point of the modal spaces by.
.[\
#
Williamson spaces possibility
.]
Stability of biological system dependent on what happens when when some state variables has low values.
This is, when individual propensities are manifesting themselves.
In evoluation we can see this in evolution in the theory of Evolutionarily Stable Strategies (ESS).
.PP
In infectious diseases we have the problem of when and if a few infected individuals can cause an epidemic.
An ESS is characterised by that when a strategy is adopted by a majority of a population no rare mutant is able to invade that population.
Here we see how the properties of few individuals are having crucial importance of the fate of the many.
Or in terms of a dynamic system,
is the equlibrium state of the system invasible or susceptibility to change.
Here is where dynamical systems theory meets modalities such as possibility and necessity.
