.LP
.dropcap Most 3 red4 R STIX 1n
of what me notice are not things that are,
but changes in what there is.
Perhaps you woke up one morning and the radio news declares that the central bank in your country had concluded that the inflation has increased to much,
and that it had to increase the interest rate.
That could make people less inclined to buy your house,
and that could lead to a decreased value of your property,
which in turn could give you problem 
