.SH
Natural Selection and our understanding of probability
.ID
From Mr. Darwin and Frater Gregor Mendel
to William Hamilton and George Price
Deriving Fisher's and Wright's equations from Price's
Mendel's laws and Hardy-Weinberg enters frequency interpretation into the dynamics
Frequency interpretation is epistemology, not metaphysics
.DE
.so natural-selection/the-price-formula.ms
.SH
Probability, possibility and dynamical systems
.ID
One locus two alleles
stability, invasibility and the role of propensities when rare
We should avoid the fitness concept (interpreted as a propensity or not)
Instead focus on selection as a process.
We are not guaranteed that the propagation of a trate can be
summarized in a single statistic
.DE
.so essay-williamson.ms
.SH
Can vi overcome the persistence forcast\[em]or how poor is historicism?
.ID
How to do better than the \f[I]persistence forcast\f[P]
Blind variation and selective retention (Campbell)
The poverty of historicism.
.DE
