.LP
There are a few issues related to numbers and mathematics.
The first one is well described by David Lewis
.QP
.vs 12
.ps 10
Another well-known problem for simple frequentism:
if spacetime is finite and chance systems get only just so small,
then all frequencies are rational numbers.
Yet the great majority of real numbers are irrational,
and we have no pre-philosophical reason to doubt that chances in a finite world can take irrational values.
.[
Humean Supervenience Debugged
.]
.LP
This is even more relevant for populations.
Ten billion human carriers of mutations is countable,
and so is the number of genes.
Hence, the number of individuals of any species on earth is natural,
it is member of $\[natnums]$,
therefore frequencies of genes and genotypes have to be rational, they must $\[mo]^\[rationals]$.
The mathematics we use for dynamical systems are real numbers,
and Karl Popper's theorems are based on his expression (reiterated here):
.EQ
p(a,b)=r,  roman where ~  r\[mo]^\[reals]
.EN
The $P( a | b )$ in Equation (1\[aq]) is also member of $\[reals]$.
We naturally accept the real numbers,
as probabilities, gene frequencies, population densities and so forth.
This attitude comes easily as long as we accept the platonic view of mathematics.
Then mathematical objects do not have real world counterparts requiring ontological commitments.
.[
Leon Horsten Mathematics
.]
.PP
However,
if the members of $\[reals]$ exist and their properties should have meaning for objects in the physical or biological world, then this raises problems.
What does it even mean that variables would have values that would take an infinite amount of time to calculate (if we were to calculate them with all their infinite decimals)?
This is one of the reasons intuitionistic mathematics does not accept them as such objects.
.[
Gisin indeterminism 
.]
