.LP
I begin while discussing an important example of an individual propensity,
namely the demographic survivorship curve.
Peter
.[\ 
#
Medawar problem biology 
.]\ 
was one of the first to explore the origin of senescence.
With that follows that the probability of survival to a given age is actually a variable that is subject to evolution,
and possible to analyse using a cost-benefit analysis.
.so ./life-tables/survivorship-curves.ms
