.LP
Causation is causal dependence with transitivity.
.[\& (
Lewis causation
.], p. 563)
Assume that we have a population growing according to some law and that its population grows from $N sub t$ one year to $N sub t+x$ the year after.
Further,
let $AA$ the dominating genotype in the population, its wild type.
This $A$ gene manifests itself on some trait called $x$.
In particular, let the $AA$ have the specific value of $x = x hat$,
and that the growth rate is affected by the value of $x$
.EQ
N sub t+x = N sub t left ( 1 + f (x , N sub t ) right )
.EN
Consider the following series of events:
.IP M
\f[B]A mutation occurs\f[P]
.br
Assume that the $A$ gene occasionally mutates $A -> a$ and that the bearers of the allele $a$ ($Aa$) have a phenotype that deviates from $x$.
.IP P
\f[B]The muation has a phenotypic effect\f[P]
.br
Assume that the mutants with genotype ($Aa$) have a modified trait where $x = 
x hat + delta x$
